version: 2.1

commands:
  run-test:
    parameters:
      testname:
        description: Runs a test specified under tests/jobs/<< testname >>.bash
        type: string

    steps:
      - run: |
          cd /BovTB-nf/
          mkdir -p /artifacts/
          bash -e tests/jobs/<< parameters.testname >>.bash

      - store_artifacts:
          path: /artifacts/

jobs:
  # Docker image containing the nextflow pipeline
  build:
    docker:
      # Circleci base ubuntu image
      - image: cimg/base:2020.01

    steps:
      - checkout
      - setup_remote_docker
      - run: |
          TAG=$CIRCLE_BRANCH
          docker build -t aaronsfishman/bov-tb:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push aaronsfishman/bov-tb:$TAG

  tinyreads:
    executor: nf-pipeline
    steps:
      - run-test:
          testname: "tinyreads"

  quality:
    executor: nf-pipeline
    steps:
      - run-test:
          testname: "quality"

executors:
  nf-pipeline:
    docker:
      - image: "aaronsfishman/bov-tb:$CIRCLE_BRANCH"

# Orchestrates sets of jobs
workflows:
  validation:
    jobs:
      - build
      - tinyreads:
          requires:
            - build
      - quality:
          requires:
            - tinyreads
