version: 2.1

commands:
  # Run tests under BovTB-nf/tests/jobs/ and store artifacts
  run-test:
    parameters:
      script:
        description: This test calls 'bash -e tests/jobs/<< script >>'
        type: string

    steps:
      - run: |
          cd /BovTB-nf/
          mkdir /reads/ /results/ /artifacts/
          bash -e tests/jobs/<< parameters.script >>

      - store_artifacts:
          path: /artifacts/

# Run tests under BovTB-nf/tests/jobs/ and store artifacts
jobs:
  # Docker image containing the nextflow pipeline
  build:
    docker:
      # Circleci base ubuntu image
      - image: cimg/base:2020.01
    parameters:
      tag:
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - run: bash -e tests/jobs/build.bash << parameters.tag >> $DOCKER_USER $DOCKER_PASS

  tinyreads:
    executor: nf-pipeline
    steps:
      - run-test:
          script: "tinyreads.bash"

  quality:
    executor: nf-pipeline
    parameters:
      case:
        type: string
    steps:
      - run-test:
          script: "quality.bash << parameters.case >>"

# Run a job on the current branch's Dockerfile
executors:
  nf-pipeline:
    docker:
      - image: "aaronsfishman/bov-tb:$CIRCLE_BRANCH"

# Orchestrates the validation tests 
workflows:
  validation:
    jobs:
      - build

      - tinyreads:
          requires:
            - build
            
      - quality:
          requires:
            - tinyreads
          matrix:
            parameters:
              case: ["low", "adequate"]
