version: 2.1

commands:
  # Run tests under BovTB-nf/tests/jobs/ and store artifacts
  run-test:
    parameters:
      script:
        description: This test calls 'bash -e tests/jobs/<< script >>'
        type: string

    steps:
      - run: |
          cd /BovTB-nf/
          mkdir /reads/ /results/ /artifacts/
          bash -e tests/jobs/<< parameters.script >>

      - store_artifacts:
          path: /artifacts/

# Run tests under BovTB-nf/tests/jobs/ and store artifacts
jobs:
  # Docker image containing the nextflow pipeline
  build:
    docker:
      # Circleci base ubuntu image
      - image: cimg/base:2020.01

    steps:
      - checkout
      - setup_remote_docker
      - run: |
          TAG=$CIRCLE_BRANCH
          docker build -t aaronsfishman/bov-tb:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push aaronsfishman/bov-tb:$TAG

  tinyreads:
    executor: nf-pipeline
    steps:
      - run-test:
          script: "tinyreads.bash"

  quality:
    executor: nf-pipeline
    parameters:
      case:
        type: string
    steps:
      - run-test:
          script: "quality.bash << parameters.case >>"

# Run a job on the current branch's Dockerfile
executors:
  nf-pipeline:
    docker:
      - image: "aaronsfishman/bov-tb:$CIRCLE_BRANCH"

# Orchestrates the validation tests 
workflows:
  validation:
    jobs:
      - build
      - tinyreads:
          requires:
            - build
      - quality:
          case: low
          requires:
            - tinyreads
      - quality:
          case: adequate
          requires:
            - tinyreads

