# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t aaronsfishman/bov-tb:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push aaronsfishman/bov-tb:$TAG


# Orchestrate or schedule a set of jobs
workflows:
  build_docker:
    jobs:
      - build
  # # Name the workflow "welcome"
  # welcome:
  #   # Run the welcome/run job in its own container
  #   jobs:
  #     - welcome/run

