version: 2.1

jobs:
  # Docker image containing the nextflow pipeline
  build:
    docker:
      # Circleci base ubuntu image
      - image: cimg/base:2020.01

    steps:
      - checkout

      - setup_remote_docker

      # build and push Docker image
      - run: |
          TAG=$CIRCLE_BRANCH
          docker build -t aaronsfishman/bov-tb:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push aaronsfishman/bov-tb:$TAG

  minimal-reads:
    executor: nf-pipeline
    working_directory: /BovTB-nf/
    steps:
      - run: "bash -e tests/jobs/minimal-pipeline.bash"
      - store_artifacts:
          path: /results/report.html
          destination: report.html

executors:
  nf-pipeline:
    docker:
      - image: "aaronsfishman/bov-tb:$CIRCLE_BRANCH"

# Orchestrates sets of jobs
workflows:
  validation:
    jobs:
      - build
      - minimal-reads:
          requires:
            - build
