version: 2.1

jobs:
  # Docker image containing the nextflow pipeline
  build:
    docker:
      # Circleci base ubuntu image
      - image: cimg/base:2020.01

    steps:
      - checkout

      - setup_remote_docker

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t aaronsfishman/bov-tb:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push aaronsfishman/bov-tb:$TAG

# Orchestrates sets of jobs
workflows:
  build:
    jobs:
      - build

