version: 2.1

jobs:
  # Docker image containing the nextflow pipeline
  build:
    docker:
      # Circleci base ubuntu image
      - image: cimg/base:2020.01

    steps:
      - checkout

      - setup_remote_docker

      # build and push Docker image
      - run: |
          TAG=$CIRCLE_BRANCH
          docker build -t aaronsfishman/bov-tb:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push aaronsfishman/bov-tb:$TAG

  minimal-reads:
    executor: nf-pipeline
    working_directory: /BovTB-nf/
    steps:
      - run: |
          mkdir /results/
          ln -s $PWD/tests/minimal-read-pair/ /reads
          nextflow run bTB-WGS_process.nf --outdir "/results/" --reads "/reads/*_{S*_R1,S*_R2}*.fastq.gz"
          WGS_CLUSTER_CSV=/results/`sh tests/utils/print_todays_wgs_cluster.sh`
          python tests/utils/assert_first_csv_row.py $WGS_CLUSTER_CSV Outcome InsufficientData

executors:
  nf-pipeline:
    docker:
      - image: "aaronsfishman/bov-tb:$CIRCLE_BRANCH"

# Orchestrates sets of jobs
workflows:
  validation:
    jobs:
      - build
      - minimal-reads:
          requires:
            - build
